import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans, DM_Serif_Display } from 'next/font/google';

// Google Font
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights you need
  variable: "--font-dm-sans", // Optional custom variable name
});

const dmSerifDisp = DM_Serif_Display({
  subsets: ["latin"],
  weight: ["400"], // Specify weights you need
  variable: "--font-dm-sans", // Optional custom variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${dmSerifDisp.variable} ${dmSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}